# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/SoLU-Notebook-Test',
                'doc_host': 'https://neelnanda-io.github.io',
                'git_url': 'https://github.com/neelnanda-io/SoLU-Notebook-Test',
                'lib_path': 'SoLU_Notebook_Test'},
  'syms': {'SoLU_Notebook_Test.core': {'SoLU_Notebook_Test.core.foo': ('core.html#foo', 'SoLU_Notebook_Test/core.py')}}}